version: '3'

services:
  web:
    image: mohassan844/tmdb_app:latest # Replace with your Docker Hub username and app name
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/reactapp.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
