version: '3'

services:
  react_app:
    image: mohassan844/tmdb_app:latest # Replace with your Docker Hub username and app name
    container_name: react_app
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./reverseproxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react_app