name: Node.js CI

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Linter
      run: npm run lint || true
     
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --passWithNoTests || true

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          mohassan844/tmdb_app:latest
          mohassan844/tmdb_app:${{ github.run_number }}
        file: Dockerfile

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'